In [1]:
import pandas as pd
import os
import glob
import numpy as np

In [2]:
archives_dir_path = "./parquet_files/"

In [3]:
df = pd.DataFrame()

In [4]:
df2 = pd.read_parquet("./parquet_files/yellow_tripdata_2023-01.parquet")

In [5]:
df2.columns.values

array(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID',
       'store_and_fwd_flag', 'PULocationID', 'DOLocationID',
       'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount',
       'tolls_amount', 'improvement_surcharge', 'total_amount',
       'congestion_surcharge', 'airport_fee'], dtype=object)

In [6]:
df2

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN

In [18]:
for file_path in glob.glob(os.path.join(archives_dir_path, "*.parquet")):
    if df.empty:
        df = pd.read_parquet(file_path)

        lowercase_array = np.array([s.lower() for s in df.columns.values])
        
        rename_dict = dict(zip(df.columns.values, lowercase_array))
        df.rename(rename_dict, inplace=True)
    else:
        df_aux = pd.read_parquet(file_path)

        lowercase_array = np.array([s.lower() for s in df_aux.columns.values])
        
        rename_dict = dict(zip(df_aux.columns.values, lowercase_array))
        df_aux.rename(rename_dict, inplace=True)
        
        df = pd.concat([df, df_aux])
        break
    print(file_path)

./parquet_files\yellow_tripdata_2023-12.parquet

In [19]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,NaN
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,NaN
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,NaN
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,NaN
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913950,2,2023-02-28 23:46:00,2023-03-01 00:05:00,NaN,4.65,NaN,None,249,140,0,20.22,0.00,0.5,4.84,0.0,1.0,29.06,NaN,NaN,NaN
2913951,2,2023-02-28 23:26:02,2023-02-28 23:37:10,NaN,2.47,NaN,None,186,79,0,13.66,0.00,0.5,2.65,0.0,1.0,20.31,NaN,NaN,NaN
2913952,2,2023-02-28 23:24:00,2023-02-28 23:38:00,NaN,3.49,NaN,None,158,143,0,17.64,0.00,0.5,0.00,0.0,1.0,21.64,NaN,NaN,NaN
2913953,2,2023-02-28 23:03:00,2023-02-28 23:10:00,NaN,2.13,NaN,None,79,162,0,13.56,0.00,0.5,2.63,0.0,1.0,20.19,NaN,NaN,NaN
2913954,2,2023-02-28 23:03:03,2023-02-28 23:12:51,NaN,2.28,NaN,None,161,140,0,14.89,0.00,0.5,3.78,0.0,1.0,22.67,NaN,NaN,NaN

In [7]:
df = pd.read_parquet(archives_dir_path+"yellow_tripdata_2023-07.parquet")

In [8]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-07-01 00:29:59,2023-07-01 00:40:15,1.0,1.80,1.0,N,140,263,1,12.10,3.5,0.5,5.10,0.0,1.0,22.20,2.5,0.0
1,2,2023-07-01 00:03:25,2023-07-01 00:23:44,1.0,2.31,1.0,N,163,163,2,19.10,1.0,0.5,0.00,0.0,1.0,24.10,2.5,0.0
2,2,2023-07-01 00:38:29,2023-07-01 00:48:53,1.0,2.36,1.0,N,142,262,1,13.50,1.0,0.5,3.70,0.0,1.0,22.20,2.5,0.0
3,2,2023-07-01 00:14:16,2023-07-01 00:29:13,1.0,4.36,1.0,N,68,24,1,19.80,1.0,0.5,4.96,0.0,1.0,29.76,2.5,0.0
4,1,2023-07-01 00:11:15,2023-07-01 00:20:47,0.0,1.60,1.0,N,161,107,1,11.40,3.5,0.5,3.25,0.0,1.0,19.65,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2907103,2,2023-07-31 23:18:11,2023-07-31 23:18:23,NaN,0.00,NaN,None,106,106,0,21.58,0.0,0.5,0.00,0.0,1.0,23.08,NaN,NaN
2907104,2,2023-07-31 23:29:31,2023-07-31 23:51:17,NaN,4.97,NaN,None,238,243,0,22.12,0.0,0.5,0.00,0.0,1.0,23.62,NaN,NaN
2907105,2,2023-07-31 23:16:57,2023-07-31 23:17:25,NaN,0.03,NaN,None,141,141,0,23.93,0.0,0.5,0.00,0.0,1.0,27.93,NaN,NaN
2907106,2,2023-07-31 23:29:00,2023-07-31 23:46:00,NaN,3.24,NaN,None,65,62,0,9.54,0.0,0.5,3.00,0.0,1.0,14.04,NaN,NaN
2907107,2,2023-07-31 23:34:13,2023-07-31 23:48:51,NaN,2.08,NaN,None,162,143,0,14.33,0.0,0.5,0.00,0.0,1.0,18.33,NaN,NaN